---
# tasks file for molecule_demo

- name: Include OS family related variables
  include_vars:
    file: '{{ ansible_distribution }}.yml'

- name: Include OS distribution related tasks
  include_tasks: '{{ ansible_distribution }}.yml'

- name: Install pip dependencies
  pip:
    name:
      - pip==20.1
      - setuptools==44.0.0
      - wheel==0.33.6
    extra_args: "-vvv"

- name: echo hello world
  debug:
    msg: hello world

- name: set file contents fact
  set_fact:
    hello_world: "hello world, dated: {{ ansible_date_time.iso8601 }}"

- name: this is what the file will contain
  debug: var=hello_world

- name: let them know we were here  # noqa 301
  shell: >
    echo "{{ hello_world }}" > \
    /tmp/hello.world
  args:
    creates: /tmp/hello.world

- name: install Molecule
  pip:
    name: "Molecule==2.22"
    state: present
