---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: centos7
    image: geerlingguy/docker-centos7-ansible
  - name: ubuntu18
    image: geerlingguy/docker-ubuntu1804-ansible
  - name: fedora29
    image: geerlingguy/docker-fedora29-ansible
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  config_options:
    defaults:
      stdout_callback: yaml
verifier:
  name: testinfra
  lint:
    name: flake8
